misago/admin/urls.py
from django.conf.urls import url

from misago import admin

from .views import auth, index


urlpatterns = [
    # "misago:admin:index" link symbolises "root" of Misago admin links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago Admin and will be checked by Misago Admin Middleware
    url(r'^$', index.admin_index, name='index'),
    url(r'^resolve-version/$', index.check_version, name='check-version'),
    url(r'^logout/$', auth.logout, name='logout'),
]

# Discover admin and register patterns
admin.discover_misago_admin()
urlpatterns += admin.urlpatterns()

misago/project_template/project_name/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.decorators.http import last_modified
from django.views.i18n import JavaScriptCatalog

from misago.users.forms.auth import AdminAuthenticationForm


admin.autodiscover()
admin.site.login_form = AdminAuthenticationForm


urlpatterns = [
    url(r'^', include('misago.urls', namespace='misago')),

    # Javascript translations
    url(
        r'^django-i18n.js$',
        last_modified(lambda req, **kw: timezone.now())(
            cache_page(86400 * 2, key_prefix='misagojsi18n')(
                JavaScriptCatalog.as_view(
                    packages=['misago'],
                ),
            ),
        ),
        name='django-i18n',
    ),

    # Uncomment next line if you plan to use Django admin for 3rd party apps
    #url(r'^django-admin/', admin.site.urls),
]


# If debug mode is enabled, include debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


# Use static file server for static and media files (debug only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Error Handlers
# Misago needs those handlers to deal with errors raised by it's middlewares
# If you replace those handlers with custom ones, make sure you decorate them
# with shared_403_exception_handler or shared_404_exception_handler
# decorators that are defined in misago.views.errorpages module!
handler403 = 'misago.core.errorpages.permission_denied'
handler404 = 'misago.core.errorpages.page_not_found'

misago/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from misago.conf import settings
from misago.core.views import forum_index


app_name = 'misago'

# Register Misago Apps
urlpatterns = [
    url(r'^', include('misago.legal.urls')),
    url(r'^', include('misago.users.urls')),
    url(r'^', include('misago.categories.urls')),
    url(r'^', include('misago.threads.urls')),
    url(r'^', include('misago.search.urls')),

    # default robots.txt
    url(
        r'^robots.txt$',
        TemplateView.as_view(content_type='text/plain', template_name='misago/robots.txt')
    ),

    # "misago:index" link symbolises "root" of Misago links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago and will be handled by misago.views.exceptionhandler if it
    # results in Http404 or PermissionDenied exception
    url(r'^$', forum_index, name='index'),
]


# Register API
apipatterns = [
    url(r'^', include('misago.categories.urls.api')),
    url(r'^', include('misago.markup.urls')),
    url(r'^', include('misago.threads.urls.api')),
    url(r'^', include('misago.users.urls.api')),
    url(r'^', include('misago.search.urls.api')),
]

urlpatterns += [
    url(r'^api/', include((apipatterns, 'api'), namespace='api')),
]


# Register Misago ACP
if settings.MISAGO_ADMIN_PATH:
    # Admin patterns recognised by Misago
    adminpatterns = [
        url(r'^', include('misago.admin.urls')),
    ]

    admin_prefix = r'^%s/' % settings.MISAGO_ADMIN_PATH
    urlpatterns += [
        url(admin_prefix, include((adminpatterns, 'admin'), namespace='admin')),
    ]

misago/templates/misago/admin/base.html
{% extends "misago/admin/base_thin.html" %}
{% load static %}


{% block body %}
{% include "misago/admin/navbar.html" %}
{% include "misago/admin/messages.html" %}

{% block content %}{% endblock %}

<footer class="admin-footer">
  <div class="misago-branding text-center">
    <a href="http://misago-project.org">
      <span class="subscript">powered by</span>
      <img src="{% static 'misago/admin/img/misago.png' %}" height="22px" alt="Misago">
    </a>
  </div>
</footer>

{% include "misago/admin/logout.html" %}

{# We include JavaScript at the end of page body so it renders faster #}
<script type="text/javascript" src="{% static 'misago/admin/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-datetimepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-timestamps.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tooltips.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tables.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-yesnoswitch.js' %}"></script>
{% block javascripts %}{% endblock javascripts %}
{% endblock body %}

misago/templates/misago/admin/base_thin.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% trans "Misago Administration" %}{% endblock %}</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'misago/admin/css/style.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-touch-icon-57.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-touch-icon-72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-touch-icon-76.png' %}">
    <link rel="apple-touch-icon" sizes="80x80" href="{% static 'apple-touch-icon-80.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-touch-icon-114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-touch-icon-120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-touch-icon-144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-touch-icon-152.png' %}">
    <link rel="apple-touch-icon" sizes="167x167" href="{% static 'apple-touch-icon-167.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon-180.png' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="icon" sizes="16x16 32x32" href="{% static 'favicon.ico' %}">
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        
        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        
        tr:nth-child(even) {
            background-color: #dddddd;
        }
        </style>
  </head>
  <body>

    {% block body %}{% endblock %}

  </body>
</html>

misago/templates/misago/admin/index.html
{% extends "misago/admin/base.html" %}
{% load i18n %}


{% block title %}{% trans "Home" %} | {{ block.super }}{% endblock %}


{% block content %}
<div class="page-header">
  <div class="container">
    <h1>
      <span class="fa fa-home"></span>
      {% trans "Administration Home" %}
    </h1>
  </div>
  
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div id="admin-content-index">
        <table title="Reports" id='report-table'>
            <tr>
              <th>Report Link</th>
              <th>Report Type</th>
              <th>Reporter</th>
            </tr>
            <tbody id="table_notification"></tbody>
          </table>
      </div>
    </div>
    <div class="col-md-4">

      <table class="table version-check">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-github"></span>
                {% trans "Misago version" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center">
              {% if allow_version_check %}
                {% if version_check %}
                <p class="lead text-{% if version_check.is_error %}danger{% else %}success{% endif %}">
                  {% if version_check.is_error %}
                  <span class="fa fa-times fa-lg fa-fw"></span>
                  {% else %}
                  <span class="fa fa-check fa-lg fa-fw"></span>
                  {% endif %}
                  {{ version_check.message }}
                </p>
                {% else %}
                <form method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-default">
                    <span class="fa fa-question-circle fa-fw"></span>
                    <span class="name">{% trans "Check version" %}</span>
                  </button>
                </form>
                {% endif %}
              {% else %}
                <p class="lead">
                  {% trans 'This feature requires "packaging" python module.' %}
                </p>
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>

      <table class="table">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-database"></span>
                {% trans "DB Contents" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{% trans "Threads" %}</td>
            <td>{{ db_stats.threads }}</td>
          </tr>
          <tr>
            <td>{% trans "Posts" %}</td>
            <td>{{ db_stats.posts }}</td>
          </tr>
          <tr>
            <td>{% trans "Users" %}</td>
            <td>{{ db_stats.users }}</td>
          </tr>
          {% if db_stats.inactive_users %}
          <tr>
            <td>{% trans "Inactive users" %}</td>
            <td>
              <a href="{% url "misago:admin:users:accounts:index" %}?inactive=1">{{ db_stats.inactive_users }}</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>

    </div>
  </div>
</div>
<script>

</script>
{% endblock content %}


{% block javascripts %}
<script type="text/javascript">
  $(function () {
    var $version_check = $('.version-check');
    var $outcome = $version_check.find('td');

    $version_check.find('form').submit(function() {
      var $form = $(this);
      var $button = $(this).find("button");
      $button.attr("disabled", "disabled");
      $button.find('.fa').attr("class", "fa fa-refresh fa-fw fa-spin");
      $button.find('.name').text("{% trans "Checking..." %}");

      $.post("{% url 'misago:admin:check-version' %}", $form.serialize(), function(data) {
        if (data.is_error) {
          var $message = $('<p class="lead text-danger"><span class="fa fa-times fa-lg fa-fw"></span></p>');
        } else {
          var $message = $('<p class="lead text-success"><span class="fa fa-check fa-lg fa-fw"></span></p>');
        }
        $message.append(" " + data.message);
        $form.fadeOut();
        $outcome.html($message);
      });

      return false;
    });
  });

  $( document ).ready(function() {
    populateNotifications();
});
function populateNotifications() {
    var data =[]
    $.ajax({
        url: '/api/threads/1/get_all_reports/',
        dataType: "json",
        type: 'get',
        success: function (responseText) {
            for (var record in responseText) {
                id = "<td>"+ "<a href=/t"+responseText[record].report_id+">" + responseText[record].report_id + "</a>"+"</td>"
                type = "<td>"+responseText[record].report_type+"</td>"
                user_id = "<td>"+responseText[record].reported_by+"</td>"
                row = "<tr>"+id+ type + user_id +"</tr>"
                $("#table_notification").append(row)
            }
        },
        error: function (responseText) {
            console.log(responseText)
        }
    });
}
</script>
{% endblock javascripts %}

misago/templates/misago/admin/login.html
{% extends "misago/admin/base_thin.html" %}
{% load i18n static %}


{% block title %}{% trans "Log in" %} | {% if target == "django" %}{% trans "Django Admin" %}{% else %}{% trans "Misago Admin" %}{% endif %}{% endblock %}


{% block body %}
<div class="login-form">

  {% if target == "misago" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/misago.png' %}" alt="Misago">
  </div>
  {% elif target == "django" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/django.png' %}" alt="Django">
  </div>
  {% endif  %}

  <div class="form-panel">
    <form method="POST" role="form">
      {% csrf_token %}

      <div class="form-header">
        <h1>{% trans "Administration" %}</h1>
      </div>

      <div class="form-body no-fieldsets">

        {% for error in form.non_field_errors %}
        <div class="misago-alerts">
          <p class="alert alert-danger lead">
            {{ error }}
            <br>{% trans "Please try again." %}
          </p>
        </div>
        {% endfor %}
        {% for message in messages %}
        <div class="misago-alerts">
          {% if 'success' in message.tags %}
          <p class="alert alert-success lead">
          {% elif 'warning' in message.tags %}
          <p class="alert alert-warning lead">
          {% elif 'error' in message.tags %}
          <p class="alert alert-danger lead">
          {% else %}
          <p class="alert alert-info lead">
          {% endif %}
            {{ message }}
          </p>
        </div>
        {% endfor %}

        <div class="form-group">
          <div class="control-input">
            <input type="text" name="username" class="form-control input-lg" placeholder="{% trans "Username or e-mail" %}" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <input type="password" name="password" class="form-control input-lg" placeholder="{% trans "Password" %}">
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <button class="btn btn-primary btn-block btn-lg">{% trans "Sign in" %}</button>
          </div>
        </div>

      </div>


    </form>
  </div>

</div>
{% endblock body %}

misago/templates/misago/admin/logout.html
{% load i18n %}
<!-- Log out modal -->
<div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="logoutModalLabel">{% trans "Log out?" %}</h4>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-md-6">

            <form action="{% url 'misago:admin:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block">
                <span class="fa fa-lock"></span>
                {% trans "Log out from admin" %}
              </button>
            </form>

          </div>
          <div class="col-md-6">

            <form action="{% url 'misago:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-block">
                <span class="fa fa-power-off"></span>
                {% trans "Log out completely" %}
              </button>
            </form>

          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-lg btn-block" data-dismiss="modal">{% trans "Cancel" %}</button>
      </div>
    </div>
  </div>
</div>

misago/templates/misago/admin/messages.html
{% load i18n %}
{% if messages %}
<div class="misago-alerts">
  {% for message in messages %}
  <div>
    {% if 'info' in message.tags %}
    <p class="alert alert-info">
      <span class="alert-icon fa fa-info-circle"></span>
    {% elif 'success' in message.tags %}
    <p class="alert alert-success">
      <span class="alert-icon fa fa-check-circle"></span>
    {% elif 'warning' in message.tags %}
    <p class="alert alert-warning">
      <span class="alert-icon fa fa-exclamation-triangle"></span>
    {% elif 'error' in message.tags %}
    <p class="alert alert-danger">
      <span class="alert-icon fa fa-times-circle"></span>
    {% endif %}
      {{ message }}
    </p>
  </div>
  {% endfor %}
</div>
{% endif %}

misago/templates/misago/admin/navbar.html
{% load i18n misago_avatars %}
<div class="navbars-container">
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <a class="navbar-brand" href="{% url 'misago:index' %}"></a>
      <ul class="nav navbar-nav">
        {% for node in sections %}
        <li{% if node.is_active %} class="active"{% endif %}>
          <a href="{{ node.link }}">
            <span class="{{ node.icon }}"></span>
            {{ node.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
      <div class="user-nav pull-right">
        <p class="navbar-text">
          <a href="{% url 'misago:admin:users:accounts:edit' pk=user.pk %}" class="tooltip-bottom" title="{% trans "Edit your account" %}">
            <img src="{{ user|avatar:30 }}" alt="{% trans "Your avatar" %}">
            {{ user }}
          </a>
          <a href="#" class="logout" data-toggle="modal" data-target="#logout-modal">
            <span class="fa fa-power-off"></span>
          </a>
        </p>
      </div>
    </div>
  </div>
  {% if actions %}
  <div class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav">
        {% for node in actions %}
        <li{% if node.is_active %} class="active"{% endif %}>
          <a href="{{ node.link }}">
            <span class="{{ node.icon }}"></span>
            {{ node.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
</div>

misago/templates/misago/admin/permissions_table.html
{% load crispy_forms_field crispy_forms_tags i18n %}
<fieldset>
  <legend>{{ form.legend }}</legend>

  <table class="table table-striped table-permissions">
    {% for field in form %}
    <tr{% if field.errors %} class="text-danger"{% endif %}>
      <td class="col-md-8">
        <label>{{ field.label }}:</label>
        {% for error in field.errors %}
        <p class="small"><strong>{{ error }}</strong></p>
        {% endfor %}
        {% if field.help_text %}
        <p class="text-muted small">{{ field.help_text }}</p>
        {% endif %}
      </td>
      <td>
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap3/layout/checkboxselectmultiple.html' %}
          {% endif %}

          {% if field|is_radioselect %}
            {% include 'bootstrap3/layout/radioselect.html' with hide_help_text=1 %}
          {% endif %}

          {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
          {% crispy_field field %}
          {% endif %}
        </div>
      </td>
    </tr>
    {% endfor %}
  </table>

</fieldset>